clear-on-join: true
pickup-items: true
join-teleport: true
fall-damage: true
deny-saturation: true
deny-drops: true
items-on-join: true
deny-build: true
respawn-time: 5
xp-per-kill: 5
arrow-shot-message: true
regeneration-soup-value: 5.0
kit-default: 'pvp'
scoreboard:
  enable: true
  update-ticks: 20
database:
  enable: false
  database-name: 'database'
  table: 'simplesoups'
  user: 'root'
  ip: 'localhost'
  password: 'mypassword'
items-join:
  kits:
    material: CHEST
    slot: 0
    display: '&aKits &e(Right click)'
    lore:
      - '&7Open menu of kits, select'
      - '&7one and go fight!'
items:
  permission-boolean:
    true: '&aAllow'
    false: '&cDeny'
  locked-kit:
    material: BEDROCK
    display: '&cLocked kit &e(Right click)'
    lore:
      - '&7This kit is locked, if'
      - '&7you will get this kit, please buy!'
      - '&r'
      - '&aPrice: &c$%value%'
signs:
  soups: '&8[&cKitPvP&8];&cSoups'
sounds:
  death-countdown:
    enable: true
    sound: NOTE_SNARE_DRUM
    vol: 10
    pitch: 5
commands:
  enable: true
  allow-commands:
    - '/soup'
    - '/kits'
    - '/kit'
