name: SimpleSoups
version: ${project.version}
main: me.gardendev.simplesoups.SimpleSoups
authors: [ Jonakls ]
commands:
  soup:
    aliases:
      - soupvp
      - pvp
      - spvp
      - kit
      - kits
    description: General command