name: SimpleSoups
version: ${version}
main: me.jonakls.simplesoups.SimpleSoups
authors: [ Jonakls ]
commands:
  soup:
    aliases:
      - soupvp
      - pvp
      - spvp
      - kit
      - kits
    description: General command